import '../model/e_mart_product_model.dart';

class Globals {
  static bool data = false;
  static List<Product> products = [
    Product(
      id: 1,
      name: "IPhone 9\n - SmartPhone",
      price: 549,
      image: "assets/images/1.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 2,
      name: "IPhone X\n - SmartPhone",
      price: 899,
      image: "assets/images/2.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 3,
      name: "Iphone 11 Pro\n - SmartPhone",
      price: 1099,
      quantity: 0,
      image: "assets/images/3.png",
      like: "false",
    ),
    Product(
      id: 4,
      name: "IPhone 12\n - SmartPhone",
      price: 1299,
      image: "assets/images/4.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 5,
      name: "XPS 13\n - Laptops",
      price: 999,
      image: "assets/images/5.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 6,
      name: "Latitude 5540\n - Laptops",
      price: 1189,
      image: "assets/images/6.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 7,
      name: "HP EliteBook\n - Laptops",
      price: 1909,
      image: "assets/images/7.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 8,
      name: "HP 14\n - Laptops",
      price: 199,
      image: "assets/images/8.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 9,
      name: "Google Pixel\n - SmartWatches",
      price: 289,
      image: "assets/images/9.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 10,
      name: "Keyo SE\n - SmartWatches",
      price: 161,
      image: "assets/images/10.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 11,
      name: "Samsung\n - SmartWatches",
      price: 100,
      image: "assets/images/11.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 12,
      name: "Z GPAX\n - SmartWatches",
      price: 199,
      image: "assets/images/12.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 13,
      name: "Studio Pro\n - HeadPhones",
      price: 23,
      image: "assets/images/13.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 14,
      name: "Studio Pro X\n - HeadPhones",
      price: 30,
      image: "assets/images/14.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 15,
      name: "AirPods Max\n - HeadPhones",
      price: 40,
      image: "assets/images/15.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 16,
      name: "Vacuum Tube\n - HeadPhones",
      price: 60,
      image: "assets/images/16.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 17,
      name: "IPad 8th gen\n - IPad",
      price: 200,
      image: "assets/images/17.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 18,
      name: "IPad Mini\n - IPad",
      price: 200,
      image: "assets/images/18.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 19,
      name: "IPad Air\n - IPad",
      price: 50,
      image: "assets/images/19.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 20,
      name: "IPad 10th Gen\n - IPad",
      price: 20,
      image: "assets/images/20.jpg",
      quantity: 0,
      like: "false",
    ),
    ];
}