// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwzRE5Bwp1Ao0u3TW6FrD9Htk2STe6t5I',
    appId: '1:4839210077:web:0783c809d33063030d21b4',
    messagingSenderId: '4839210077',
    projectId: 'electronic-mart-ce09c',
    authDomain: 'electronic-mart-ce09c.firebaseapp.com',
    storageBucket: 'electronic-mart-ce09c.appspot.com',
    measurementId: 'G-MBFS7YL6Q1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5oRm0CukOXbK3S7XmlThKZ9NmpxcoypA',
    appId: '1:4839210077:android:2ae0e0e98e67ed6f0d21b4',
    messagingSenderId: '4839210077',
    projectId: 'electronic-mart-ce09c',
    storageBucket: 'electronic-mart-ce09c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdouN9i5cOZ2oGcbdMNyJ6ThbqBrCsalQ',
    appId: '1:4839210077:ios:426b42492441b0f30d21b4',
    messagingSenderId: '4839210077',
    projectId: 'electronic-mart-ce09c',
    storageBucket: 'electronic-mart-ce09c.appspot.com',
    iosClientId: '4839210077-tf0bq26o2v3mubelkii1odghb0vabdu6.apps.googleusercontent.com',
    iosBundleId: 'com.app.eMart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdouN9i5cOZ2oGcbdMNyJ6ThbqBrCsalQ',
    appId: '1:4839210077:ios:bce32b6fd98bf8d00d21b4',
    messagingSenderId: '4839210077',
    projectId: 'electronic-mart-ce09c',
    storageBucket: 'electronic-mart-ce09c.appspot.com',
    iosClientId: '4839210077-n90uvuenmftso0jdb8perbmh1rjjg37q.apps.googleusercontent.com',
    iosBundleId: 'com.app.eMart.RunnerTests',
  );
}
